import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header/Header'
import Footer from '../components/Footer/Footer'
import Hero from '../components/Hero/Hero'
import Projects from '../components/Projects/Projects'
import Skills from '../components/Skills/Skills'
import About from '../components/About/About'
import Link from 'next/link'


const Home: NextPage = () => {
  return (
    <div
      className='z-0 h-screen overflow-scroll snap-madatory scrollbar-thumb-gray-900 scrollbar-track-gray-400/20 scrollbar-thin'>
      <Head>
        <title>Nhi's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Background /> */}
      <Header />
      <section id='hero' className='snap-start'>
      <Hero />
      </section>
      <section id='about' className='snap-center'>
      <About />
      </section>
      <section id='skills' >
      <Skills />
      </section>
      <section id='projects' className='snap-center'>
      <Projects />
      </section>
      <section id='contact' className='snap-center'>
        <Footer />
      </section>
      <Link href="#hero">
        <footer className='sticky w-full cursor-pointer bottom-5'>
          <div className='flex items-center justify-center'>
            <img
              className='h-10 rounded-full cursor-pointer grayscale hover:grayscale-0'
              src='../images/Avatar.png' />
          </div>
        </footer>
      </Link>

    </div>
  )
}

export default Home;

